# ============================================================================
# K8s on Hetzner Cloud — k3s + Cloud LB + Multi-DC + Autoscaler
# ============================================================================

terraform {
  required_version = ">= 1.5.0"
  required_providers {
    hcloud = {
      source  = "hetznercloud/hcloud"
      version = ">= 1.49.0, < 2.0.0"
    }
    tls = {
      source  = "hashicorp/tls"
      version = ">= 4.0.0, < 5.0.0"
    }
    random = {
      source  = "hashicorp/random"
      version = ">= 3.6.0, < 4.0.0"
    }
    null = {
      source  = "hashicorp/null"
      version = ">= 3.2.0, < 4.0.0"
    }
    external = {
      source  = "hashicorp/external"
      version = ">= 2.3.0, < 3.0.0"
    }
  }
}

provider "hcloud" {
  token = var.hcloud_token
}

# ============================================================================
# Local values for common labels
# ============================================================================

locals {
  common_labels = {
    cluster     = var.cluster_name
    managed_by  = "terraform"
    environment = "production"
  }

  # Pre-render cloud-init templates so we can validate YAML before provisioning
  server_cloud_init = templatefile("${path.module}/cloud-init-server.yaml.tpl", {
    hcloud_token             = var.hcloud_token
    cluster_name             = var.cluster_name
    network_name             = hcloud_network.cluster.name
    k3s_channel              = var.k3s_channel
    worker_fetch_pubkey      = tls_private_key.worker_fetch.public_key_openssh
    etcd_encryption_key      = base64encode(random_password.etcd_encryption_key.result)
    enable_wireguard         = var.enable_wireguard
    wireguard_server_privkey = random_id.wireguard_server_key.b64_std
    wireguard_client_pubkey  = var.wireguard_client_public_key
    wireguard_client_ip      = var.wireguard_client_ip
  })

  agent_cloud_init = templatefile("${path.module}/cloud-init-agent.yaml.tpl", {
    control_plane_ip     = "10.0.1.1"
    k3s_channel          = var.k3s_channel
    worker_fetch_privkey = tls_private_key.worker_fetch.private_key_openssh
  })
}

# ============================================================================
# SSH Key
# ============================================================================

resource "hcloud_ssh_key" "default" {
  name       = "${var.cluster_name}-key"
  public_key = file(var.ssh_public_key_path)

  labels = local.common_labels
}

# Generate a dedicated key pair for worker→control-plane token fetch
resource "tls_private_key" "worker_fetch" {
  algorithm = "ED25519"
}

# ============================================================================
# Wireguard Server Key (generated by Terraform)
# ============================================================================

resource "random_id" "wireguard_server_key" {
  byte_length = 32
}

# Generate etcd encryption key
resource "random_password" "etcd_encryption_key" {
  length  = 32
  special = false
}

# ============================================================================
# Network (spans eu-central zone: fsn1, nbg1, hel1)
# ============================================================================

resource "hcloud_network" "cluster" {
  name     = "${var.cluster_name}-network"
  ip_range = "10.0.0.0/16"

  labels = local.common_labels

  lifecycle {
    prevent_destroy = false
  }
}

resource "hcloud_network_subnet" "nodes" {
  network_id   = hcloud_network.cluster.id
  type         = "cloud"
  network_zone = var.network_zone
  ip_range     = "10.0.1.0/24"
}

# ============================================================================
# Firewall
# ============================================================================

resource "hcloud_firewall" "cluster" {
  name = "${var.cluster_name}-fw"

  labels = local.common_labels

  lifecycle {
    prevent_destroy = false
  }

  # SSH
  rule {
    direction   = "in"
    protocol    = "tcp"
    port        = "22"
    source_ips  = ["0.0.0.0/0", "::/0"]
    description = "SSH"
  }

  # HTTP (via LB)
  rule {
    direction   = "in"
    protocol    = "tcp"
    port        = "80"
    source_ips  = ["0.0.0.0/0", "::/0"]
    description = "HTTP"
  }

  # HTTPS
  rule {
    direction   = "in"
    protocol    = "tcp"
    port        = "443"
    source_ips  = ["0.0.0.0/0", "::/0"]
    description = "HTTPS"
  }

  # Wireguard VPN
  rule {
    direction   = "in"
    protocol    = "udp"
    port        = "51820"
    source_ips  = ["0.0.0.0/0", "::/0"]
    description = "Wireguard VPN"
  }

  # K8s API — ONLY from Wireguard subnet (secure) and private network
  rule {
    direction   = "in"
    protocol    = "tcp"
    port        = "6443"
    source_ips  = ["10.200.200.0/24", "10.0.0.0/16"]
    description = "Kubernetes API (Wireguard + internal only)"
  }

  # ============================================================================
  # Internal cluster traffic (specific ports instead of "any")
  # ============================================================================

  # K8s API (internal)
  rule {
    direction   = "in"
    protocol    = "tcp"
    port        = "6443"
    source_ips  = ["10.0.0.0/16"]
    description = "Internal K8s API"
  }

  # Kubelet API
  rule {
    direction   = "in"
    protocol    = "tcp"
    port        = "10250"
    source_ips  = ["10.0.0.0/16"]
    description = "Kubelet API"
  }

  # etcd (control plane only)
  rule {
    direction   = "in"
    protocol    = "tcp"
    port        = "2379-2380"
    source_ips  = ["10.0.0.0/16"]
    description = "etcd cluster"
  }

  # Flannel VXLAN
  rule {
    direction   = "in"
    protocol    = "udp"
    port        = "8472"
    source_ips  = ["10.0.0.0/16"]
    description = "Flannel VXLAN"
  }

  # NodePort range (for services)
  rule {
    direction   = "in"
    protocol    = "tcp"
    port        = "30000-32767"
    source_ips  = ["10.0.0.0/16"]
    description = "NodePort services"
  }

  # Metrics server
  rule {
    direction   = "in"
    protocol    = "tcp"
    port        = "10251-10252"
    source_ips  = ["10.0.0.0/16"]
    description = "Kube scheduler/controller metrics"
  }

  # CoreDNS
  rule {
    direction   = "in"
    protocol    = "tcp"
    port        = "53"
    source_ips  = ["10.0.0.0/16"]
    description = "CoreDNS TCP"
  }

  rule {
    direction   = "in"
    protocol    = "udp"
    port        = "53"
    source_ips  = ["10.0.0.0/16"]
    description = "CoreDNS UDP"
  }

  # ICMP (PMTUD, ping)
  rule {
    direction   = "in"
    protocol    = "icmp"
    source_ips  = ["0.0.0.0/0", "::/0"]
    description = "ICMP (PMTUD, ping)"
  }

  # ============================================================================
  # Egress rules (explicit allow)
  # ============================================================================

  rule {
    direction       = "out"
    protocol        = "tcp"
    port            = "443"
    destination_ips = ["0.0.0.0/0", "::/0"]
    description     = "HTTPS outbound (apt, registries, APIs)"
  }

  rule {
    direction       = "out"
    protocol        = "tcp"
    port            = "80"
    destination_ips = ["0.0.0.0/0", "::/0"]
    description     = "HTTP outbound (apt)"
  }

  rule {
    direction       = "out"
    protocol        = "udp"
    port            = "53"
    destination_ips = ["0.0.0.0/0", "::/0"]
    description     = "DNS outbound"
  }

  rule {
    direction       = "out"
    protocol        = "tcp"
    port            = "53"
    destination_ips = ["0.0.0.0/0", "::/0"]
    description     = "DNS TCP outbound"
  }

  # NTP
  rule {
    direction       = "out"
    protocol        = "udp"
    port            = "123"
    destination_ips = ["0.0.0.0/0", "::/0"]
    description     = "NTP outbound"
  }

  # ICMP (required for Path MTU Discovery)
  rule {
    direction       = "out"
    protocol        = "icmp"
    destination_ips = ["0.0.0.0/0", "::/0"]
    description     = "ICMP (required for PMTUD)"
  }

  # Wireguard VPN outbound (keepalives)
  rule {
    direction       = "out"
    protocol        = "udp"
    port            = "51820"
    destination_ips = ["0.0.0.0/0", "::/0"]
    description     = "Wireguard VPN outbound"
  }

  # Internal cluster egress
  rule {
    direction       = "out"
    protocol        = "tcp"
    port            = "any"
    destination_ips = ["10.0.0.0/16"]
    description     = "Internal cluster egress TCP"
  }

  rule {
    direction       = "out"
    protocol        = "udp"
    port            = "any"
    destination_ips = ["10.0.0.0/16"]
    description     = "Internal cluster egress UDP"
  }
}

# ============================================================================
# Control Plane Node (always on, in fsn1)
# ============================================================================

resource "hcloud_server" "control_plane" {
  name         = "${var.cluster_name}-cp-1"
  image        = "ubuntu-24.04"
  server_type  = var.server_type
  location     = var.control_plane_location
  ssh_keys     = [hcloud_ssh_key.default.id]
  firewall_ids = [hcloud_firewall.cluster.id]

  labels = merge(local.common_labels, {
    role = "control-plane"
  })

  lifecycle {
    prevent_destroy = false

    precondition {
      condition     = can(yamldecode(local.server_cloud_init))
      error_message = "cloud-init-server.yaml.tpl rendered invalid YAML. Check template for syntax errors (e.g. multi-line values breaking indentation)."
    }
  }

  network {
    network_id = hcloud_network.cluster.id
    ip         = "10.0.1.1"
  }

  user_data = local.server_cloud_init

  depends_on = [hcloud_network_subnet.nodes]
}

# ============================================================================
# Initial Worker Nodes (optional, for testing without autoscaler)
# Distributed round-robin across worker_locations
# ============================================================================

resource "hcloud_server" "worker" {
  count        = var.initial_worker_count
  name         = "${var.cluster_name}-worker-${count.index + 1}"
  image        = "ubuntu-24.04"
  server_type  = var.server_type
  location     = var.worker_locations[count.index % length(var.worker_locations)]
  ssh_keys     = [hcloud_ssh_key.default.id]
  firewall_ids = [hcloud_firewall.cluster.id]

  labels = merge(local.common_labels, {
    role                = "worker"
    "hcloud/node-group" = "workers"
  })

  lifecycle {
    precondition {
      condition     = can(yamldecode(local.agent_cloud_init))
      error_message = "cloud-init-agent.yaml.tpl rendered invalid YAML. Check template for syntax errors."
    }
  }

  network {
    network_id = hcloud_network.cluster.id
    ip         = "10.0.1.${count.index + 10}"
  }

  user_data = local.agent_cloud_init

  depends_on = [hcloud_server.control_plane]
}

# ============================================================================
# Load Balancer (in fsn1, routes to all nodes)
# ============================================================================

resource "hcloud_load_balancer" "ingress" {
  name               = "${var.cluster_name}-lb"
  load_balancer_type = "lb11" # 25 targets, 5 certs
  location           = var.control_plane_location

  labels = local.common_labels

  lifecycle {
    prevent_destroy = false
  }
}

resource "hcloud_load_balancer_network" "ingress" {
  load_balancer_id = hcloud_load_balancer.ingress.id
  network_id       = hcloud_network.cluster.id
  ip               = "10.0.1.254"
}

# Control plane is always a target (runs workloads since workers can scale to 0)
resource "hcloud_load_balancer_target" "control_plane" {
  type             = "server"
  load_balancer_id = hcloud_load_balancer.ingress.id
  server_id        = hcloud_server.control_plane.id
  use_private_ip   = true
  depends_on       = [hcloud_load_balancer_network.ingress]
}

# Initial workers as LB targets
resource "hcloud_load_balancer_target" "workers" {
  count            = var.initial_worker_count
  type             = "server"
  load_balancer_id = hcloud_load_balancer.ingress.id
  server_id        = hcloud_server.worker[count.index].id
  use_private_ip   = true
  depends_on       = [hcloud_load_balancer_network.ingress]
}

# Label selector for autoscaled workers (CCM will add them automatically)
resource "hcloud_load_balancer_target" "label_selector" {
  type             = "label_selector"
  load_balancer_id = hcloud_load_balancer.ingress.id
  label_selector   = "cluster=${var.cluster_name},role=worker"
  use_private_ip   = true
  depends_on       = [hcloud_load_balancer_network.ingress]
}

# TCP passthrough — TLS terminates at Traefik, not the LB
resource "hcloud_load_balancer_service" "http" {
  load_balancer_id = hcloud_load_balancer.ingress.id
  protocol         = "tcp"
  listen_port      = 80
  destination_port = 80
  proxyprotocol    = true

  health_check {
    protocol = "tcp"
    port     = 80
    interval = 10
    timeout  = 5
    retries  = 3
  }
}

resource "hcloud_load_balancer_service" "https" {
  load_balancer_id = hcloud_load_balancer.ingress.id
  protocol         = "tcp"
  listen_port      = 443
  destination_port = 443
  proxyprotocol    = true

  health_check {
    protocol = "tcp"
    port     = 443
    interval = 10
    timeout  = 5
    retries  = 3
  }
}

# ============================================================================
# Wait for K3s to be ready and fetch kubeconfig
# ============================================================================

resource "null_resource" "wait_for_k3s" {
  depends_on = [hcloud_server.control_plane]

  connection {
    type        = "ssh"
    user        = "root"
    host        = hcloud_server.control_plane.ipv4_address
    private_key = file(replace(var.ssh_public_key_path, ".pub", ""))
  }

  provisioner "remote-exec" {
    inline = [
      "echo 'Waiting for cloud-init to complete...'",
      "cloud-init status --wait || true",
      "echo 'Waiting for k3s to be ready...'",
      "TIMEOUT=600; ELAPSED=0; until kubectl get nodes --kubeconfig /etc/rancher/k3s/k3s.yaml 2>/dev/null; do sleep 5; ELAPSED=$((ELAPSED+5)); if [ $ELAPSED -ge $TIMEOUT ]; then echo 'TIMEOUT waiting for k3s'; exit 1; fi; done",
      "echo 'K3s is ready!'"
    ]
  }
}

# Fetch kubeconfig from control plane
data "external" "kubeconfig" {
  depends_on = [null_resource.wait_for_k3s]

  program = ["bash", "-c", <<-EOF
    KUBECONFIG=$(ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ConnectTimeout=30 \
      -i ${replace(var.ssh_public_key_path, ".pub", "")} \
      root@${hcloud_server.control_plane.ipv4_address} \
      "cat /etc/rancher/k3s/k3s.yaml" 2>/dev/null | \
      sed 's|127.0.0.1|${var.enable_wireguard ? "127.0.0.1" : hcloud_server.control_plane.ipv4_address}|g')
    if [ -z "$KUBECONFIG" ]; then
      echo "ERROR: Failed to fetch kubeconfig via SSH" >&2
      exit 1
    fi
    echo "{\"kubeconfig\": $(echo "$KUBECONFIG" | jq -Rs .)}"
  EOF
  ]
}

# Fetch WireGuard server public key (derived on server from private key)
data "external" "wireguard_server_pubkey" {
  count      = var.enable_wireguard ? 1 : 0
  depends_on = [null_resource.wait_for_k3s]

  program = ["bash", "-c", <<-EOF
    PUBKEY=$(ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ConnectTimeout=30 \
      -i ${replace(var.ssh_public_key_path, ".pub", "")} \
      root@${hcloud_server.control_plane.ipv4_address} \
      "cat /etc/wireguard/server.pub" 2>/dev/null)
    if [ -z "$PUBKEY" ]; then
      echo "ERROR: Failed to fetch WireGuard public key via SSH" >&2
      exit 1
    fi
    echo "{\"pubkey\": \"$(echo $PUBKEY | tr -d '\n')\"}"
  EOF
  ]
}

# ============================================================================
# WireGuard Tunnel (auto-setup on local machine)
# ============================================================================

resource "null_resource" "wireguard_tunnel" {
  count      = var.enable_wireguard ? 1 : 0
  depends_on = [data.external.wireguard_server_pubkey]

  triggers = {
    server_pubkey = data.external.wireguard_server_pubkey[0].result.pubkey
    endpoint      = hcloud_server.control_plane.ipv4_address
    client_ip     = var.wireguard_client_ip
  }

  lifecycle {
    precondition {
      condition     = var.wireguard_client_private_key != ""
      error_message = "wireguard_client_private_key is required when enable_wireguard is true. Generate with: wg genkey"
    }
    precondition {
      condition     = var.wireguard_client_public_key != ""
      error_message = "wireguard_client_public_key is required when enable_wireguard is true. Generate with: wg genkey | tee privatekey | wg pubkey"
    }
  }

  provisioner "local-exec" {
    command     = <<-EOF
      # Write wireproxy config (userspace WireGuard, no root needed)
      cat > .wireproxy.conf << WPEOF
      [Interface]
      Address = ${var.wireguard_client_ip}/32
      PrivateKey = ${var.wireguard_client_private_key}

      [Peer]
      PublicKey = ${data.external.wireguard_server_pubkey[0].result.pubkey}
      Endpoint = ${hcloud_server.control_plane.ipv4_address}:51820
      AllowedIPs = 10.200.200.0/24, 10.0.0.0/16
      PersistentKeepalive = 25

      [TCPClientTunnel]
      BindAddress = 127.0.0.1:6443
      Target = 10.200.200.1:6443
      WPEOF
      chmod 600 .wireproxy.conf

      # Kill existing wireproxy if running
      if [ -f .wireproxy.pid ]; then
        kill $(cat .wireproxy.pid) 2>/dev/null || true
      fi

      # Start wireproxy in background
      nohup wireproxy -c .wireproxy.conf > .wireproxy.log 2>&1 &
      echo $! > .wireproxy.pid

      # Verify K8s API is reachable through tunnel
      echo "Waiting for wireproxy tunnel..."
      for i in $(seq 1 30); do
        if bash -c "echo >/dev/tcp/127.0.0.1/6443" 2>/dev/null; then
          echo "Wireproxy tunnel established"
          exit 0
        fi
        sleep 2
      done
      echo "ERROR: Wireproxy tunnel failed - check .wireproxy.log" >&2
      exit 1
    EOF
    interpreter = ["bash", "-c"]
  }

  provisioner "local-exec" {
    when    = destroy
    command = <<-EOF
      if [ -f .wireproxy.pid ]; then
        kill $(cat .wireproxy.pid) 2>/dev/null || true
        rm -f .wireproxy.pid .wireproxy.conf .wireproxy.log
      fi
    EOF
    interpreter = ["bash", "-c"]
    on_failure  = continue
  }
}
