# ============================================================================
# Outputs
# ============================================================================

output "control_plane_public_ip" {
  description = "Public IPv4 of the control plane"
  value       = hcloud_server.control_plane.ipv4_address
}

output "control_plane_private_ip" {
  description = "Private IP of the control plane"
  value       = "10.0.1.1"
}

output "load_balancer_ip" {
  description = "Public IPv4 of the load balancer (use for DNS)"
  value       = hcloud_load_balancer.ingress.ipv4
}

output "worker_public_ips" {
  description = "Public IPs of initial worker nodes"
  value       = hcloud_server.worker[*].ipv4_address
}

output "kubevirt_worker_public_ip" {
  description = "Public IPv4 of the KubeVirt worker node"
  value       = var.enable_windows_vm ? hcloud_server.kubevirt_worker[0].ipv4_address : null
}

# ============================================================================
# Kubeconfig (from Talos provider)
# ============================================================================

output "kubeconfig" {
  description = "Kubeconfig for cluster access (save to ~/.kube/hetzner-k8s.yaml)"
  value       = talos_cluster_kubeconfig.this.kubeconfig_raw
  sensitive   = true
}

output "kubeconfig_command" {
  description = "Command to save and use kubeconfig"
  value       = <<-EOT
    # Save kubeconfig:
    terraform output -raw kubeconfig > ~/.kube/hetzner-k8s.yaml
    chmod 600 ~/.kube/hetzner-k8s.yaml

    # Use it:
    export KUBECONFIG=~/.kube/hetzner-k8s.yaml
    kubectl get nodes
  EOT
}

# ============================================================================
# Talos Configuration
# ============================================================================

output "talosconfig" {
  description = "Talos client configuration for talosctl"
  value       = data.talos_client_configuration.this.talos_config
  sensitive   = true
}

# ============================================================================
# DNS Instructions
# ============================================================================

output "dns_instructions" {
  description = "Manual DNS setup in Cloudflare"
  value       = <<-EOT

    Add these A records in Cloudflare (DNS-only mode, gray cloud):

    | Type | Name   | Value          |
    |------|--------|----------------|
    | A    | *.k8s  | ${hcloud_load_balancer.ingress.ipv4} |
    | A    | k8s    | ${hcloud_load_balancer.ingress.ipv4} |

    Point your wildcard domain to the LB IP for ingress routing.

  EOT
}

# ============================================================================
# Passwords (generated by Terraform, stored in state)
# ============================================================================

output "windows_admin_password" {
  description = "Windows Administrator password"
  value       = random_password.windows_admin.result
  sensitive   = true
}

output "guacamole_password" {
  description = "Guacamole web UI admin password"
  value       = random_password.guacamole.result
  sensitive   = true
}

output "grafana_password" {
  description = "Grafana admin password"
  value       = random_password.grafana.result
  sensitive   = true
}

output "argocd_initial_admin_password" {
  description = "Command to retrieve ArgoCD initial admin password"
  value       = "kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath='{.data.password}' | base64 -d"
}

# ============================================================================
# Quick Reference
# ============================================================================

output "summary" {
  description = "Deployment summary"
  value       = <<-EOT

    Hetzner K8s Cluster (Talos Linux + ArgoCD GitOps) Deployed!
    =============================================================

    Control Plane: ${hcloud_server.control_plane.ipv4_address} (${var.control_plane_location})
    Load Balancer: ${hcloud_load_balancer.ingress.ipv4}
    Initial Workers: ${var.initial_worker_count}
    Talos Version: ${var.talos_version}

    ArgoCD manages all workloads from git (app-of-apps pattern).

    Next Steps:
    1. Run: ./scripts/post-deploy.sh  (fetches kubeconfig, shows status)
    2. Add DNS records (see dns_instructions output)
    3. Check ArgoCD: kubectl -n argocd get applications
    4. ArgoCD UI: kubectl -n argocd port-forward svc/argocd-server 8080:80
    5. Deploy test app: kubectl apply -f manifests/example-app.yaml

    Retrieve passwords:
      terraform output -raw windows_admin_password
      terraform output -raw guacamole_password
      terraform output -raw grafana_password

    Security Notes:
    - K8s API (6443) accessible only via WireGuard VPN
    - Talos API (50000) accessible only via WireGuard VPN
    - No SSH — manage via talosctl through WireGuard tunnel

  EOT
}
