apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-autoscaler
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.repoURL }}
    targetRevision: {{ .Values.targetRevision }}
    path: gitops/apps/autoscaler
  destination:
    server: https://kubernetes.default.svc
    namespace: cluster-autoscaler
  {{- include "root-app.syncPolicy" . | nindent 2 }}
