{{- if .Values.enableWindows }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubevirt-cr
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.repoURL }}
    targetRevision: {{ .Values.targetRevision }}
    path: gitops/apps/kubevirt-cr
  destination:
    server: https://kubernetes.default.svc
    namespace: kubevirt
  {{- include "root-app.syncPolicy" . | nindent 2 }}
{{- end }}
