apiVersion: v1
kind: ConfigMap
metadata:
  name: zellij-config
  namespace: browsh
data:
  config.kdl: |
    default_mode "locked"
    keybinds clear-defaults=true {
      locked {
        // no keybindings — cannot unlock
      }
    }
