apiVersion: cdi.kubevirt.io/v1beta1
kind: CDI
metadata:
  name: cdi
spec:
  config:
    featureGates:
    - HonorWaitForFirstConsumer
    - WebhookPvcRendering
  imagePullPolicy: IfNotPresent
  infra:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: kubevirt
              operator: In
              values:
              - "true"
    nodeSelector:
      kubernetes.io/os: linux
      kubevirt: "true"
    tolerations:
    - key: kubevirt
      operator: Equal
      value: "true"
      effect: NoSchedule
  workload:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: kubevirt
              operator: In
              values:
              - "true"
    nodeSelector:
      kubernetes.io/os: linux
      kubevirt: "true"
    tolerations:
    - key: kubevirt
      operator: Equal
      value: "true"
      effect: NoSchedule
