apiVersion: clickhouse.altinity.com/v1
kind: ClickHouseInstallation
metadata:
  name: plausible-clickhouse
  annotations:
    plausible/reconcile-trigger: "2"
spec:
  configuration:
    users:
      plausible/password:
        valueFrom:
          secretKeyRef:
            name: plausible-credentials
            key: CLICKHOUSE_PASSWORD
      plausible/networks/ip: "::/0"
      plausible/profile: default
      plausible/quota: default
    clusters:
      - name: plausible
        layout:
          shardsCount: 1
          replicasCount: 1
    settings:
      logger/level: warning
  defaults:
    templates:
      dataVolumeClaimTemplate: data
  templates:
    volumeClaimTemplates:
      - name: data
        spec:
          storageClassName: hcloud-volumes
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
