apiVersion: clickhouse.altinity.com/v1
kind: ClickHouseInstallation
metadata:
  name: plausible-clickhouse
  annotations:
    plausible/reconcile-trigger: "1"
spec:
  configuration:
    users:
      default/networks/ip: "::/0"
    clusters:
      - name: plausible
        layout:
          shardsCount: 1
          replicasCount: 1
    settings:
      logger/level: warning
  defaults:
    templates:
      dataVolumeClaimTemplate: data
  templates:
    volumeClaimTemplates:
      - name: data
        spec:
          storageClassName: hcloud-volumes
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
