apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  name: plausible-postgres
spec:
  podAnnotations:
    plausible/restart-trigger: "2"
  teamId: plausible
  volume:
    size: 5Gi
    storageClass: hcloud-volumes
  numberOfInstances: 1
  users:
    plausible: []
  databases:
    plausible: plausible
  patroni:
    pg_hba:
      - local   all all trust
      - hostssl all all 0.0.0.0/0 md5
      - host    all all 0.0.0.0/0 md5
      - hostssl all all ::/0 md5
      - host    all all ::/0 md5
  postgresql:
    version: "16"
    parameters:
      ssl: "off"
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
