apiVersion: apps/v1
kind: Deployment
metadata:
  name: kwatch
  namespace: kwatch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kwatch
  template:
    metadata:
      labels:
        app: kwatch
    spec:
      serviceAccountName: kwatch
      containers:
        - name: kwatch
          image: ghcr.io/abahmed/kwatch:v0.10.3
          env:
            - name: CONFIG_FILE
              value: /config/config.yaml
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 64Mi
          volumeMounts:
            - name: config
              mountPath: /config/config.yaml
              subPath: config.yaml
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: kwatch
