apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-apache-config
data:
  blog-alias.conf: |
    Alias /blog /var/www/html
    <Directory /var/www/html>
      AllowOverride All
      Require all granted
      RewriteEngine On
      RewriteBase /blog/
      RewriteRule ^index\.php$ - [L]
      RewriteCond %{REQUEST_FILENAME} !-f
      RewriteCond %{REQUEST_FILENAME} !-d
      RewriteRule . /blog/index.php [L]
    </Directory>
