# KubeVirt CR with workload tolerations for dedicated VM node
---
apiVersion: kubevirt.io/v1
kind: KubeVirt
metadata:
  name: kubevirt
  namespace: kubevirt
spec:
  configuration:
    developerConfiguration:
      useEmulation: true
  infra:
    nodePlacement:
      nodeSelector:
        kubevirt: "true"
      tolerations:
        - key: kubevirt
          operator: Equal
          value: "true"
          effect: NoSchedule
  workloads:
    nodePlacement:
      nodeSelector:
        kubevirt: "true"
      tolerations:
        - key: kubevirt
          operator: Equal
          value: "true"
          effect: NoSchedule
